### PR TITLE
handle restoration of windows environment variables correctly

### LINKED ISSUE #2286: GoInstallBinaries does not work and breaks $PATH on windows
### What did you do? (required: The issue will be **closed** when not provided)

```
:echo executable("go.exe")
1
:GoInstallBinaries
# Errors:
# vim-go: could not find 'go'. Run :GoInstallBinaries to fix it

:echo executable("go.exe")
0
```

### What did you expect to happen?
Go tools binaries are installed

### What happened instead?
Fails

### Configuration (**MUST** fill this out):
Windows 10 x64
Dein and nothing else

#### vim-go version:
I have bisected it and the commit that breaks it seems to be https://github.com/fatih/vim-go/pull/2255
https://github.com/fatih/vim-go/commit/dd882abf345f04bef4e6318e90cc3c7078f78825

This works fine on vim-go v1.19 and is broken in vim-go v1.20
This seems to be similar to unresolved #2257

Workaround for dein:
```
call dein#add('fatih/vim-go', { 'rev': 'v1.19' })
" or
call dein#add('fatih/vim-go', { 'rev': '45cdcc10aa81a61c0c5bfb2059e844e9dd10d176' })
```

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
set runtimepath+=~/.nvim/repos/github.com/Shougo/dein.vim
set runtimepath+=~/.nvim/

if dein#load_state('~/.nvim/')
  call dein#begin('~/.nvim/')
  " Let dein manage dein
  " Required:
  call dein#add('~/.nvim/repos/github.com/Shougo/dein.vim')
endif

call dein#add('fatih/vim-go')
</pre></details>

#### Vim version (first three lines from `:version`):
Neovim 0.4.0 and 0.3.5

####  Go version (`go version`):
1.12.5

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Gleb\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Gleb\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Gleb\AppData\Local\Temp\go-build422699794=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### PR DESCRIPTION
**Pull request by bhcleek**
Fixes #2286

### CODE REVIEW

**Comment by bhcleek** [comment]
@glebtv @aidanbrumsickle can you confirm that this works for you?

**Comment by aidanbrumsickle** [comment]
Looks good.

Deleted a few Go tool binaries and ran `:GoInstallBinaries` and it worked. I then did `:GoBuild` to make sure the `go` executable was still available, which it was, and I did `:echo $PATH` afterward and it was fine. Running `:GoUpdateBinaries` now since I believe that calls the same function.

**Comment by bhcleek** [comment]
Thank you for the assistance!

**Comment by aidanbrumsickle** [comment]
Thanks for fixing it so quickly! I use this plugin all the time and it's been getting better and better.

**Comment by bhcleek** [comment]
Thank you for the accolades. I'm trying hard to maintain high quality and resolve existing issues before adding anything new.

**Pull request merged**
