### PR TITLE
Add deoplete source

### PR DESCRIPTION
**Pull request by zchee**
Add python file for deoplete.nvim.

deoplete is, 

> Dark powered asynchronous completion framework for neovim

https://github.com/Shougo/deoplete.nvim/

It will display the completion list faster than parse `omnifunc`.

===

FYI, Now it will be override completion list in omnifunc by the implementation of deoplete.
but, If this PR is merged, @Shougo takes care of editing the deoplete side.

### CODE REVIEW

**Comment by fatih** [comment]
Hi @zchee 

Please give me more detail why we need to add this? What happens if we add it? Just please give me more context.

**Comment by zchee** [comment]
@fatih OK.
I will give you the more details, screencast and sample nvimrc for the deoplete.

Or, If you are used to the `docker`, I will give you to Dockerfile all required to operate the deoplete.
How do you like it?

**Comment by fatih** [comment]
@zchee oh no, thanks :) I've already installed deoplete before to use it with NeoVim. I just want to know why this is needed. Because I've used deploete with neovim and vim-go, everything was already working.

**Comment by zchee** [comment]
@fatih All right.
I will comment later.

**Comment by mattn** [comment]
I wonder what the advantage? Could you keep it on Shougo's repo? I'm not user of deoplete. And I'm not prefer updating for that just bugfix or update of deoplete.

**Comment by zchee** [comment]
@mattn Hmm...
but, @Shougo said that file does not include the deoplete.
This file should be kept because the user local?

Wait for @Shougo 's opinion.

/cc @Shougo

**Comment by mattn** [comment]
@zchee then, please do it yourself.

```
NeoBundle 'Shougo/deoplete'
NeoBundle 'zchee/vim-go-deoplete'
NeoBundle 'faith/vim-go'
```

I'm not make sure this is right. And I'm not a well-informed about deoplete. But if it's possible to separate from this repository, do it please.

**Comment by zchee** [comment]
@mattn I understand.
So, I will create my own repository after closing this PR.

@fatih I described for deoplete source details in the new repository. Please look if you are interested in faster completion.

**Comment by mattn** [comment]
@zchee I suggest you to make pull-request for doc to link your new repository.

**Comment by zchee** [comment]
@mattn Thanks.

Now @fatih developing the integration of neovim job control. https://github.com/fatih/vim-go/pull/607
Because I think make PR for linking my repository after `nvim` branch has been merged into the `master`.

**Comment by svanharmelen** [comment]
@zchee would be interested in a package for adding that file as well if neither `deoplete` or `vim-go` find a way to incorporate it in one of their packages... Managing the file manually doesn't make sense, so in that case making a separated package seems the way to go.

**Pull request closed without merging**
