### PR TITLE
Add iferr

### PR DESCRIPTION
**Pull request by mattn**
iferr

### CODE REVIEW

**Comment by mattn** [comment]
I will update doc in later.

**Comment by fatih** [comment]
This is cool! @mattn looking forward to the doc. If you can't make it let me know, I'll add it myself after merging.

**Comment by fatih** [comment]
@mattn would it possible to create also a `:GoIfErr` command (with the doce)? Not all vim-go users are advanced users and they heavily use commands. They know how to map commands to mappings.

**Comment by fatih** [comment]
Thanks @koron and @mattn. This is just great! :)

**Pull request merged**
