### PR TITLE
:GoExtract using godoctor

### PR DESCRIPTION
**Pull request by laher**
Introduces an 'extract function'/'extract method' feature into vim-go. 

I think this feature belongs in vim-go simply because it's such a useful refactor, and [from conversations over the years] relatively few people seem to use godoctor.vim. It's much more likely to get used if bundled with all the other vim-go goodness.

This functionality has been copied from https://github.com/godoctor/godoctor.vim (please and thanks to @joverbey ) , and then slightly adapted:

 * https://github.com/godoctor/godoctor.vim/blob/master/ftplugin/go.vim copied to `vim-go/autoload/go/godoctor.vim`
 * functions renamed from `s:snake_case` to `go:godoctor:CamelCase`.
 * the rest of the integration has been implemented in keeping with other vim-go integrations (mappings, `s:packages`, etc)

I feel like I could go a bit further with renames and such, but I'd appreciate some guidance at this point. 

So, questions:
 * Would this be an welcome feature addition for vim-go?
 * Are there any licencing issues to resolve? godoctor and godoctor.vim both use BSD 3-Clause "New" or "Revised" License.
 * Please note a TODO for a more general `:GoDoctor` command. godoctor has a few refactors available, and I feel like those could maybe be introduced later. There's some feature-overlap there with gorename, so it feels wise to postpone that feature for the time being. Sounds good?

Thanks

### CODE REVIEW

**Comment by laher** [comment]
Sorry, I don't know how to fix the remaining linting error.

```
Running vim-vimlint ... FAILED
/home/travis/build/fatih/vim-go/autoload/go/godoctor.vim:161:13:Error: EVP_E492: Not an editor command: 1,$delete
```

I tried this change:

```
-    silent :1,$delete
+    silent exec 1,$delete
```

but it still fails:

```
Running vim-vimlint ... FAILED
/home/am/d/vim-go/autoload/go/godoctor.vim:161:18:Error: EVP_0: unexpected token: ,
````

I'll take another look when I have more time

**Comment by bhcleek** [comment]
adding all of godoctor seems pretty heavy for simply adding a command to extract some code to a new function. We already have `:GoFreevars`, which will at least identify the variables that would need to be passed into the new function. Instead of bringing in a completely different style of viml and adding yet another tool to be installed and managed, perhaps we can add the new command by using guru's freevars...

**Comment by bhcleek** [comment]
First, let me start by apologizing for not saying thank you first thing last time. Sincerely, thank you for the contribution to vim-go.

You make some good points @laher. I'll take a closer look at this PR in the next week or so and get back to you. I'll also need some time to experiment with godoctor to see if it's stable enough to be used by vim-go.

**Comment by laher** [comment]
Thanks for doing that, and thank _you_ for stepping up to the plate in Fatih's absence. vim-go is a wonderful and unique project, and honestly it's reassuring to see you're considering things carefully :)

**Comment by bhcleek** [comment]
It looks like godoctor makes some simple mistakes, and I'm reluctant to add it. For instance, the way it deals with strings is problematic. Given
```
package main

import "fmt"

func main() {
    msg := "foo"
    fmt.Println(msg)

   msg += "bar"
   fmt.Println(msg)
}
```
and trying to extract the last line to a new function named `quux`, one ends up with 

```
package main

import "fmt"

func main() {
	msg := "foo"
	fmt.Println(msg)

	msg += "bar"
	quux()
}

func quux() {
	msg := "bar"
	fmt.Println(msg)
}
```

I appreciate the contribution, though. I've refactored your changes to be more vim-go-esque in case you'd like to see them: https://github.com/fatih/vim-go/commit/b4cd4b8ae4cbfc29e6e2459f93a35757cc5d9cd3

**Comment by laher** [comment]
@bhcleek after reflecting on this topic, I started a project `regopher` this week which is going to offer some refactoring tools, and it's written using Dave Brophy's 'dst' to do the source manipulation. All things considered, progress is flying already.

See https://github.com/laher/regopher.vim (and https://github.com/laher/regopher )

It's super green and limited right now (2 half-baked but operational refactoring tools), but it works. This is my first vim plugin, but 99% of the plugin code was lifted from the amazing vim-go. I've atributed in the README and attached vim-go's license. Still, please let me know if you'd rather I did something a bit differently, and I'll do what I can. 

In the meantime I'd just like to let you know that I've done this, and that my aim is to write a plugin to live alongside vim-go, with a vague idea that regopher.vim 's features might eventually be submitted to become part of vim-go in the future. 

That's a very long way off and may not even cover desirable features for the vim-go project, but I figure you might be interested in the project either way.

*Note that I have also done my best to avoid naming collisions, for global variables, commands and function names. My command names will be prefixed with `ReGo...`.*. 

Cheers

**Comment by bhcleek** [comment]
That's great to see. When regopher is stable, we can consider integrating it with vim-go. In the meantime, you may consider simply forking vim-go instead of creating regopher.vim, and making your additions that there. Presumably, there'd just be a new file (`extract.vim` or `regopher.vim`?) in the `autoload/go` directory. That would set you up to be able to rebase on top of vim-go's master easily, and make the (possible) eventual PR into vim-go super easy.

In the meantime, I'd be happy to review your work as it comes along to make sure it fits with vim-go's style, conventions, etc.

**Comment by laher** [comment]
Thanks, that's a good plan and a generous offer. 

I expect my contributions to be straightforward, although I'd want to establish a strategy for introducing each feature gradually..

I'll try adding my 2 functions into a fork and then I'll submit a 'WIP' PR down the track. Cheers

**Pull request closed without merging**
