### PR TITLE
:GoImport! to import with go get

### PR DESCRIPTION
**Pull request by mattn**
Sometimes I want to add import with go-get.

### CODE REVIEW

**Comment by fatih** [comment]
Hi @mattn. Thanks for the PR. I've added long time ago an issue about this: https://github.com/fatih/vim-go/issues/412 I had something different in mid, but this is imho more suitable, it's backward compatible and it suits in the flow. Can you please modify the doc too and add the necessary new information to it? https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L164

**Comment by fatih** [comment]
Ping @mattn. If you are busy let me know, I'll do it, no worries.

**Comment by mattn** [comment]
do it please.

**Comment by mattn** [comment]
thank you

**Comment by fatih** [comment]
Thank you to @mattn :+1:

**Pull request merged**
