### PR TITLE
Active buffer relative to workdir for gometalint

### PR DESCRIPTION
**Pull request by tombee**
When `go#lint#Gometa` is triggered by autosave, we attempt to only show
lint warnings and errors that are applicable for the active buffer. This
is done by passing the path to the file represented by the active buffer
to gometalinter's `--include` option.

The existing behaviour expands the absolute path, whereas gometalinter
outputs paths that are relative to the current working directory.

This change modifies the variable used for matching so that we also use
the current working directory for matching against lint errors/warnings.

Signed-off-by: Tom Barlow <tomwbarlow@gmail.com>

### CODE REVIEW

**Comment by tombee** [comment]
I'd been fighting with this for a couple of days, wondering why `let g:go_metalinter_autosave = 1` wasn't working for me. After debugging (and learning to debug vimscript), I discovered the command that was being executed was returning no results for me on the CLI.

This looks to be caused by the modification in `gometalinter` to make using the relative path the default: https://github.com/alecthomas/gometalinter/pull/394.

I considered modifying the `--format` parameter to use `{{.Path.Abs}}` instead to maintain backward compatibility. I felt this might be a little too opinionated, and cause breakages if users wish to override that option.

I've decided to drop the `^` for matching the beginning of the path, hopefully that means that we maintain backward compatibility with older versions of `gometalinter` and continue to work with newer versions that use relative paths by default.

I'd appreciate your thoughts, I'm a total newbie at vimscript and not at all familiar with the codebase.

**Comment by Carpetsmoker** [comment]
Thanks!

The code path you modified won't get run for must users; a little bit above it is:

```
" Call gometalinter asynchronously.
if go#util#has_job() && has('lambda')
    " [..]
    call s:lint_job({'cmd': cmd})
    return
endif
```

It's only a fallback for people with older versions of Vim.

I pushed an update which should make it work for both code paths, which seems to work well in my test. I'll see if I can add some automated tests, too.

**Comment by tombee** [comment]
@Carpetsmoker Oh I see, thanks for that! 

I'm running neovim (NVIM v0.2.2), and this is the codepath I was hitting when debugging it. I guess I might be missing something in my environment to get the async runner working.

**Comment by bhcleek** [comment]
Built #1640 on top of this. Closing in favor of #1640; note that it contains all the work done here.

Thanks @tombee !

**Comment by tombee** [comment]
Thanks @bhcleek 🎉

**Pull request closed without merging**
