### PR TITLE
Fix for locationlist or quickfix list stealing focus on save.

### PR DESCRIPTION
**Pull request by mikijov**
Related to issue #1073. The issue must have regressed since the fix in #1293. The PR is simply re-adding original fix, albeit to different location since the codebase has changed.

I have fixed the tests as well. However, I am not very familiar with how vim testing works, so I would appreciate someone verifying it.

### CODE REVIEW

**Comment by bhcleek** [comment]
Thank you for the contribution!

This will affect all codepaths that populate and show the error lists, not just on save. Can you target the fix to apply only to linting that happens when saving the file?

**Comment by mikijov** [comment]
Well, here you go. Thanks for pushing me to learn a bit of vimscript. Now I feel I accomplished something (as compared to 8 hours of meetings). :-) I hope it's what you wanted.

**Comment by bhcleek** [comment]
Thanks @mikijov. On first glance, this looks right.

**Comment by bhcleek** [comment]
Thank you @mikijov . With some slight modifications, your changes have been incorporated into master as of https://github.com/fatih/vim-go/commit/eaef6f79323a3df110928020dfc877d26332c80a

**Pull request closed without merging**
