### PR TITLE
Support vimproc for godef

### PR DESCRIPTION
**Pull request by zchee**
Signed-off-by: Koichi Shiraishi <zchee.io@gmail.com>

### CODE REVIEW

**Comment by fatih** [comment]
Thanks @zchee. Looks good :+1:

**Comment by zchee** [comment]
@fatih Thanks too!
and, Congrats joined DigitalOcean :)

**Comment by fatih** [comment]
Thanks @zchee :)

**Comment by mattn** [comment]
after merged this change, godef occur error on windows.

**Pull request merged**
