### PR TITLE
exit code should be checked with 0

### LINKED ISSUE #824: GoCoverage broken in recent commit
### Actual behavior

Checkout f830d0dc170adfd7854532d571d2a0ecf818633e and try to use GoCoverage
Tests run, but coverage report doesn't appear.

See also PR #801 

### Expected behavior

Write here what you're expecting ...

### Steps to reproduce:

Please create a reproducible case of your problem. Re produce it 
with a minimal `vimrc` with all plugins disabled and only `vim-go`
enabled:

1. Open a go file that has tests
2. Checkout vim-go 1.6
3. Run GoCoverage
4. See coverage report
5. Checkout vim-go f830d0dc170adfd7854532d571d2a0ecf818633e
6. Run GoCoverage
7. No longer see coverage report

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce: NA
* vim version: 7.4
* vim-go version: Broken in f830d0dc170adfd7854532d571d2a0ecf818633e
* go version: go 1.6.2 linux/amd64

### PR DESCRIPTION
**Pull request by mattn**
Fixes #824

### CODE REVIEW

**Comment by mattn** [comment]
@bradleyfalzon Could you check this?

**Comment by bradleyfalzon** [comment]
Yes this PR resolves the issue, but I *think* there maybe still two more issues in other areas, such as L93 (https://github.com/fatih/vim-go/commit/f830d0dc170adfd7854532d571d2a0ecf818633e#diff-4), maybe lint.vim on L67 (https://github.com/fatih/vim-go/commit/f830d0dc170adfd7854532d571d2a0ecf818633e#diff-10) and perhaps asmfmt.vim on L38 (https://github.com/fatih/vim-go/commit/f830d0dc170adfd7854532d571d2a0ecf818633e#diff-1).

**Comment by mattn** [comment]
Thanks! squashed.

**Comment by fatih** [comment]
Thanks @mattn & @bradleyfalzon for the work. I'll have a plan to go over this and make it more easier to maintain.

**Pull request merged**
