### PR TITLE
Add http handler snippets

### PR DESCRIPTION
**Pull request by andrewstuart**
This just adds a couple simple snippets for creating http handler functions.

### CODE REVIEW

**Comment by fatih** [comment]
Thanks @andrewstuart 👍

**Comment by andrewstuart** [comment]
Haha, that was fast! Thanks for keeping up a great project!

**Comment by fatih** [comment]
Yeap, added it to the changelog  as well: https://github.com/fatih/vim-go/blob/master/CHANGELOG.md#17-unreleased 

Sometimes the PR's are just simple, so I can merge without any problems. You're welcome and thanks again for the contribution :)

**Comment by andrewstuart** [comment]
This should have been fixed by #843 as far as I can tell, and was just an oversight on my part when I created the snippets.

**Pull request merged**
