### PR TITLE
fmt.vim: fix fmt for buffer names existing in nonexisting directories

### PR DESCRIPTION
**Pull request by fatih**
Related problem: https://twitter.com/mitchellh/status/643174982437113860

### CODE REVIEW

**Comment by fatih** [comment]
@mitchellh does this solves your problem?

**Comment by fatih** [comment]
@guns there is a test case inside the code, I found a very simple solution, but wonder if it's due something else. Would appreciate if you could have a look at it.

**Comment by fatih** [comment]
Using this fix now for a day it's even more buggy as it changes the filepath. Abonding it. I'll look into a better solution.

**Comment by mitchellh** [comment]
Sorry I didn't get a chance to test this I just saw it now. Let me know if you have any other ideas. Thanks!

**Pull request closed without merging**
