### PR TITLE
Some improvements for :GoRun

### PR DESCRIPTION
**Pull request by hiberabyss**
1. Now will close previous `:GoRun` window when run more than one time;
2. Fix bug when there is error after running `:GoRun`.

Bug Reproduce:
1. Create directory `/tmp/gotest`
2. Create file `/tmp/gotest/test.go` with following content:

```
package main

import "fmt"

func main() {
	abc
	greating := "hello, world!"
	fmt.Printf(greating)
}
```
3.  Run `cd /tmp/gotest && nvim test.go`;
4. Run `:GoRun`;

Following result will occur:
image

The root cause is that ` s:on_exit` close wrong window, since window is switched in `go#term#newmode`.

Thanks!

### CODE REVIEW

**Comment by hiberabyss** [comment]
Hi,

Is there any suggestion for this PR?
Thanks!

**Comment by hiberabyss** [comment]
Hi @bhcleek ,

1. Need to `cd` into the directory which contain the go file with error. This condition was missed in my previous bug reproduce description, I have updated it now.
2. The bug could also be reproduced with the latest `vim-go` master branch (d2b0a234).
3. My `g:go_term_mode` setting is `botright split`.
4. My neovim version is `v0.2.3-835-g739fb93a9`. Different neovim version should have no compact.

Thanks!

**Comment by bhcleek** [comment]
With `g:go_term_mode` set to one of the options that starts with `botright` or `rightbelow`, I get a new location list every time `:GoRun` is executed. When `g:go_term_mode` is set to one of the options that starts with `leftabove` or `topleft`, I don't see any problems. I've documented what I discovered in #1720.

Interestingly, I can only get the terminal window that shown in your screenshot if I comment out https://github.com/fatih/vim-go/blob/master/autoload/go/term.vim#L118.

While I agree there is _a_ bug, I'm unable to duplicate the bug you're describing.

**Comment by bhcleek** [comment]
@hiberabyss Can you give #1721 a run and see if it resolves the issue you're seeing? I think the source of the bug you're seeing is a race condition that #1721 should resolve.

**Comment by hiberabyss** [comment]
Hi @bhcleek ,

#1721 has resolved the issue, thanks for your great work!

Currently, when `:GoRun` N times, there will be N new windows. I expect there will be only one running window even when run `:GoRun`  N times. Could this also be improved?

image

Thanks!

**Comment by bhcleek** [comment]
I'm going to look at improving that experience when I do #1412 after #1721 is merged

**Pull request closed without merging**
