### PR TITLE
Hide nagging message when there is nothing to report

### PR DESCRIPTION
**Pull request by EVODelavega**
Small fix for issue #1960

### CODE REVIEW

**Comment by bhcleek** [comment]
All async jobs should now be setting the statustype. Which jobs are you experiencing this problem with?

**Comment by bhcleek** [comment]
I see how this is happening now. Thanks for the PR!

LGTM

**Comment by EVODelavega** [comment]
@bhcleek  I've not looked at this in-depth, but I'd be curious to know where this message was coming from. If it's not too much of a pain, could you point me in the right direction? Maybe I can help to fix this in a more elegant way, instead of checking for empty strings

**Comment by bhcleek** [comment]
This was actually the _correct_ fix; the `statustype` being empty is expected in this case.

The job being executed was probably guru as a consequence of having `g:go_auto_type_info` or `g:go_auto_sameids` set, which in turns causes the `statustype` to be empty. See https://github.com/fatih/vim-go/blob/master/autoload/go/guru.vim#L137-L139

**Pull request merged**
