### PR TITLE
use CursorHold instead of CursorMove for go_auto_sameids

### PR DESCRIPTION
**Pull request by bhcleek**

### CODE REVIEW

**Comment by fatih** [comment]
I still think this is the way to do it :) What was the main reason you closed it?

**Comment by bhcleek** [comment]
Yeah, I think it's the right way to do it, but I know you had another PR in the works, and I though this would just be a distraction.

**Comment by bhcleek** [comment]
@fatih I re-opened since we both agree it's the right way to do it and a larger change that includes this hasn't been proposed yet.

**Comment by fatih** [comment]
Thanks @bhcleek I'm going over the `:GoSameIds` PR's now. Maybe I can combine all of yours (with your commits) and merge them with couple of improvements I want to make.

**Comment by bhcleek** [comment]
Yeah, they'll all merge together cleanly. Doing an octopus merge on them works great.

**Pull request merged**
