### PR TITLE
Ask for "go env"

### PR DESCRIPTION
**Pull request by Carpetsmoker**
This gives us GOPATH and such, as well as OS info. Also word things
stronger that people *must* fill this out.

### CODE REVIEW

**Comment by bhcleek** [comment]
Can we keep the request for `go version`?

**Comment by Carpetsmoker** [comment]
Oh, I thought `go env` included that; guess not. I don't know what I was smoking :-/

**Comment by bhcleek** [comment]
According to your username you were smoking carpet ;-)

**Comment by bhcleek** [comment]
LGTM

**Pull request merged**
