### PR TITLE
fmt: save folds on close

### PR DESCRIPTION
**Pull request by fatih**
Fixes: #502

### CODE REVIEW

**Comment by eapache** [comment]
:+1: works for me with or without `vim-stay` installed

**Comment by nhooyr** [comment]
Works for me as well.

**Comment by fvdnabee** [comment]
Works here also, without vim-stay.

**Comment by fatih** [comment]
Thanks for all the comment. Please use it for couple of days/weeks. This function is fairly critical so I don't want to break something here :)

**Comment by cassava** [comment]
:+1: Works for me. So excited!

**Comment by osleg** [comment]
Works for me as well.... could it be merged?

**Comment by mattn** [comment]
when user doesn't set viewdir, default value of viewdir become $VIM i.e. /usr/share/vim. So mkview! makes error. So you need to give filename for mkview!.

**Comment by eapache** [comment]
Why `mkview` uses `$VIM` and not `$HOME` on windows is beyond me...

**Pull request merged**
