### PR TITLE
play: run code from go playground snippet

### PR DESCRIPTION
**Pull request by wingyplus**
ref #353, @fatih please review it. :)

### CODE REVIEW

**Comment by fatih** [comment]
Hi @wingyplus. Thanks for PR! My idea was actually to open a new scratch buffer and paste the content to it and **then** run it. Because the reason for this is, I want to play around with it, and eventually going to share it again back with `:GoPlay`. Have a look at:

* Check out http://learnvimscriptthehardway.stevelosh.com/chapters/52.html (Scratch Splits section) to get more info
* Also we have some helper functions, which you can read to get some idea for how to creating scratch views:  https://github.com/fatih/vim-go/blob/master/autoload/go/ui.vim#L4

**Comment by wingyplus** [comment]
@fatih Thank in advice. I modified `go#ui#OpenWindow` helper function (because I grep from source, it's no where to use it.) to show real file name before save and it can modifiable. but it doesn't save to the real file. I think you will review it and discuss about solution at the lastest commit.

Thanks.

**Comment by fatih** [comment]
Thanks @wingyplus. I'm busy lately, I'll look it at soon or later.

**Comment by wingyplus** [comment]
Thanks @fatih

**Comment by fatih** [comment]
Hi @wingyplus. Just tested it and there are couple of things that needs to be fixed:

1. `:GoPlayRun` command should be available in any case, not only when a go file is opened. (Just like `:GoInstallBinaries`, etc..
2. The split window should be vertical as nowadays all displays have more space vertically instead of in the bottom of screen
3. If you call `:GoPlayRun` twice, it overrides the currently open file. Instead it should open another new vertical split view.

**Comment by wingyplus** [comment]
Thanks for comment @fatih. I'll fix tonight.

**Comment by fatih** [comment]
Any new changes for this @wingyplus? It seems we the step three in the list above is still not implemented.

**Comment by wingyplus** [comment]
@fatih Sorry, I'm very busy at the time.Currently, I implemented 1, 2 steps in last two commits (b2cfa6e, 341de9b
).

**Comment by fatih** [comment]
No worries. May be I can pick this up if it's ok for you?

**Comment by wingyplus** [comment]
Yes, you can. :)

**Comment by fatih** [comment]
I'm going to take another stab for this. Thanks @wingyplus for your previous work.

**Pull request closed without merging**
