### PR TITLE
Highlight all Go operators

### PR DESCRIPTION
**Pull request by cespare**
See #366 for context.

### CODE REVIEW

**Comment by cespare** [comment]
Hi @fatih, friendly bump :)

This has been working great for me for the past week.

**Comment by fatih** [comment]
Hi @cespare I'm currently going over the issues and PR's :) 

I've tested it and it works quite fine, just you had this one note :+1: 

>My change is too broad, though, and causes too many false positive matches. (For instance today it broke a big /* */ comment block.)

I've double checked this (for example by opening `go/src/flag/flag.go` file and it looks fine and I couldn't see any problems. I think the problem doesn't persist any more, right ?

**Comment by cespare** [comment]
Right. That note was about a previous version of this change that I made a few months ago which had a variety of small issues. I put more time and thought into this iteration and as I've used it it seems to be working well.

**Comment by fatih** [comment]
Thanks @cespare. This is a very awesome contribution :+1:

**Comment by cespare** [comment]
Glad to help. Thanks for the great plugin :)

**Pull request merged**
