### PR TITLE
goimports fails when proj symlinked in GOPATH

### PR DESCRIPTION
**Pull request by jmrodri**
Fixes Issue #1237 . Instead of using the fully qualified filename path, we just need the relative path. This allows `goimports` to always work either if the project is symlinked into the GOPATH or if it is directly checked into the GOPATH.

Tested on:
* Fedora 25
* VIM version 8.0.425
* vim-go: HEAD as of 17 March 2017

### CODE REVIEW

**Comment by jmrodri** [comment]
I will investigate why the test fails on travis but works locally.

**Comment by fatih** [comment]
You need to add the following:

```patch
diff --git a/scripts/test.sh b/scripts/test.sh
index b22fd7d..7c913ab 100755
--- a/scripts/test.sh
+++ b/scripts/test.sh
@@ -6,6 +6,7 @@ cd $(dirname $0)
 
 # install dependencies
 go get github.com/fatih/gomodifytags
+go get golang.org/x/tools/cmd/goimports
 
 # cleanup test.log
 if [ -f "test.log" ]; then

```

**Comment by fatih** [comment]
Fixed the test and merged it. Thanks for your contribution @jmrodri

**Comment by jmrodri** [comment]
@fatih thanks for creating the project. It's awesome.

**Pull request closed without merging**
