### PR TITLE
add support for goimports -srcdir in Format

### PR DESCRIPTION
**Pull request by mhamrle**
"goimports -srcdir" fixes problems with vendoring.

### CODE REVIEW

**Comment by wuman** [comment]
I can confirm that this PR works well.

**Comment by fatih** [comment]
I was going to add this as this is broken if the user uses an old version of goimports. We need somehow warn the user to update the binary.

**Comment by fatih** [comment]
I've tested it and it works well. But if you don't update your `goimports` binary it breaks vim-go. But I think it's ok to move on. This is going to be merged to master and it's not the stale version, so it's ok. Thanks @mhamrle 

Also let me put this commit here which introduces this new feature: https://github.com/golang/tools/commit/bf084ef7580ee99a5efa3086138c942aca4aefd4

**Comment by mhamrle** [comment]
I added check if `goimports --help` contains `-srcdir` argument. If not the warning message is displayed and the `srcdir` arg is not used.

**Comment by fatih** [comment]
@mhamrle I've thought about it but I think it would slow down. How did you do the check? Can you open another PR so we can talk about it ?

**Comment by fatih** [comment]
@mhamrle we can speed it up with an intermediate cache value. So we only check once, if it's available we set `goimports_updated =1` and don't check it again till the user restarts vim.

**Pull request merged**
