### PR TITLE
Add new g:go_addtags_skip_private option

### PR DESCRIPTION
**Pull request by igrmk**
Tool gomodifytags now has -skip-private option for adding tags only to public fields

This PR mirrors this option in vim config

For example you may have following struct

    type Struct struct {
        Public  int
        private int
    }

Currently GoAddTags command would add these tags

    type Struct struct {
        Public  int `json:"public"`
        private int `json:"private"`
    }

With new option it would add

    type Struct struct {
        Public  int `json:"public"`
        private int
    }

### CODE REVIEW

**Comment by bhcleek** [comment]
Given that `:GoAddTags` can take a range of line to operate on, what's the value in adding this configuration option that will apply to every invocation?

**Comment by igrmk** [comment]
I personally never need tags for private fields. So it is just much simpler for me. I don't need to select a range with this option

**Comment by bhcleek** [comment]
The flag name for gomodifytags has changed. Would you be willing to update this PR similarly?

**Comment by igrmk** [comment]
PR is updated according to new flag name

**Comment by bhcleek** [comment]
Thanks @igrmk 

Do you mind if I rebase and push a fix for a couple of nitpicks to your branch before I merge?

**Comment by igrmk** [comment]
Please go ahead! Thanks @bhcleek

**Comment by bhcleek** [comment]
Thanks for contributing @igrmk !

**Pull request merged**
